[Host]
Hostname = "localhost"

[Github]
ClientId = ""
ClientSecret = ""
AuthorizeUrl = ""
AccessTokenUrl = ""

[Mongo]
UseMongo = false
ServerUrl = "mongodb://localhost/httpcallback"
DatabaseName = "httpcallback"
